### ISSUE TITLE
dbmonster bench?

### ISSUE THREAD

**Issue by leeoniya** [pakastin/f#1]
Hey @pakastin,

Saw this lib posted in /r/javascript/, looks neat and very similar to what I'm doing with domvm[1].

You should do a dbmonster implementation to test f's speed and correctness, I'd be interested to see how it does compared to others: [2] [3] [4]. Also, check out snabbdom [5] :)

cheers!

[1] https://github.com/leeoniya/domvm
[2] http://leeoniya.github.io/domvm/test/bench/dbmonster/
[3] https://github.com/trueadm/inferno#benchmarks
[4] http://mathieuancelin.github.io/js-repaint-perfs/
[5] https://github.com/paldepind/snabbdom

**Comment by pakastin** [comment]
Hi!

Here's a simple bench against React:
http://pakastin.fi/test/f.html
http://pakastin.fi/test/react.html

Sources:
f: https://jsfiddle.net/pakastin/8ormrkf9/
React: https://jsfiddle.net/pakastin/ko0gyk9b/

I'm getting ~40 FPS with React with zigzag line and solid 60 FPS for f.
Memory heap usage is ~150 KB for React and 15 KB for f (lower is better).

DOM reordering involved, FRZR is 5 times faster than Angular (ng-repeat with key) and 10 times faster than React, f is using the exact same reorder method. That's the reason dbmonster isn't best bench to show f's speed. Reordering is where f shines the most.

I will do also the dbmonster in some point..

**Comment by leeoniya** [comment]
Nice, thanks!

Here's a domvm impl:

Monolithic: https://jsfiddle.net/195q4m4u/7/
Monolithic w/ES6: https://jsfiddle.net/195q4m4u/6/
Components: https://jsfiddle.net/195q4m4u/5/
Components w/ES6: https://jsfiddle.net/195q4m4u/8/

I'm on Windows so it's hard for me to get heap measurements using IRHydra2, chrome --js-flags="--trace-opt --trace-deopt, or other linux tools. If you run these through your heap recorder and report, I'd be very thankful :) I'm guessing it will land somewhere between f and React, maybe 30 KB?

**Comment by pakastin** [comment]
Looks really simple to use! 👍 I'm on mobile right now, I'll bench it later..

**Comment by leeoniya** [comment]
Great!

I've updated the above with ES6 versions which are even cleaner :)

**Comment by pakastin** [comment]
Btw. while at it, check out: https://jsfiddle.net/pakastin/a80srsmt/ ;)

**Comment by leeoniya** [comment]
Neat demo.

I will point out, though, that it only works because it is very carefully timed (rather than chained). Otherwise it is completely imperative and could be done just as easily without `f`, which does not provide much except a diff of the ops, the bulk of the code is POJS.

Take a look at a similar thing done in snabbdom [1]. It does transitions/anim more generally and declaratively [2] using the `hero` module [3].

[1] http://paldepind.github.io/snabbdom/examples/hero/
[2] https://github.com/paldepind/snabbdom/blob/master/examples/hero/script.js 
[3] https://github.com/paldepind/snabbdom/blob/master/modules/hero.js

**Comment by pakastin** [comment]
Yeah I know paldepind and snabbdom. Good points about chaining, that's actually something to think about. It's possible already (you can redefine View.remove inside List.update but it's a bit clumsy way of doing it. Oh, and you could also use View.mount, View.reorder and View.remove to animate in a more chained way, but I wanted to try another approach.

**Comment by pakastin** [comment]
I actually just fixed it to be more chained:
https://jsfiddle.net/pakastin/a80srsmt/

;)

**Comment by pakastin** [comment]
Btw. `setTimeout`'s are in use just to trigger the animation, I couldn't get them to start with `requestAnimationFrame`..

**Comment by leeoniya** [comment]
`requestAnimationFrame` not only coalesces multiple calls, but also cannot be used to delay since it requests the next frame. so it makes sense that it would not work.

I'm personally not too interested in animation aspects of vdom frameworks. Demos like these are cool and all, but I would never use this in a real web application. The only time anims like this are useful is in data visualization which D3 has completely nailed with SVG.

In `domvm`, i do provide view-level and node-level lifecycle hooks [1] so basics like transition/fade/slide/flip in/out is possible [2] with Promise delays, but do not intend to support complex animations out of the box beyond what can be done imperatively similar to what you do here.

[1] https://github.com/leeoniya/domvm#lifecycle-hooks-async-animation
[2] https://leeoniya.github.io/domvm/demos/lifecycle-hooks.html

**Comment by pakastin** [comment]
No I mean you cannot add init `transform` and trigger `transition` in the same frame, and even `requestAnimationFrame` doesn't work without triggering a layout by trashing, or calling `setTimeout`.

Normally, I'd use my animation helper https://github.com/pakastin/frzr/blob/master/src/animation.js, but I wanted to do it as plain as possible.

Btw. `f` doesn't use virtual dom in any way. Elements created with `f.el` are real HTMLElements and `f.list` keeps reference when `key` is added (second parameter). That's the main difference with other libraries. Another reason, why dbmonster bench doesn't make much sense..

**Comment by leeoniya** [comment]
> Another reason, why dbmonster bench doesn't make much sense..

I think the main reason it may not make sense is not because it uses the real DOM but because `f` is imperative rather than declarative, so it's up to the user to do the optimal operations on the element rather than letting the lib figure it out. It does force the user to know the optimal operations to perform in each case though.

For example, setting `parent.textContent` is slower than setting `parent.firstChild.nodeValue` for updates, but for initial creation, `parent.textContent` is faster than using `document.createTextNode` + `parent.appendChild`.

**Comment by pakastin** [comment]
[FRZR](https://frzr.js.org) is for having automatic updates, `f` is just a simple DOM creation / DOM-list diffing -helper. But nothing prevents using `firstChild.nodeValue` with `f`.

**Comment by leeoniya** [comment]
makes sense.
