### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by f** [pakastin/f#2]
I really loved the idea and this seems promising! think this needs some improvements:
- [x] Add tests. (This is so important for the contributors to test if our contributions break things or not)
- [ ] Upgrade README and add more examples with simple tutorials.

And I liked the name since it's also my username :)

**Comment by pakastin** [comment]
Hi! Great great, thanks! 😁

Let's see what the name will eventually be, `f` is just a work name 😎

**Comment by pakastin** [comment]
I just added a new demo: https://jsfiddle.net/pakastin/a80srsmt/
Better documentation & tests coming soon.. 😉

**Comment by pakastin** [comment]
Tests now added with 100 % coverage!

**Comment by pakastin** [comment]
@pakastin/f has merged to [FRZR](https://frzr.js.org) – closing this issue
